language: node_js
node_js:
    - "8.11.2"

before_install:
install:
    - npm install -g gitbook-cli

before_script:
    - gitbook install

script:
    - gitbook build
after_success:
after_failure:
before_deploy:
deploy:
after_deploy:
after_script: